<?php

namespace Baby\StatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BabyScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabyScheduleRepository extends EntityRepository
{
}
