<?php

namespace Baby\StatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayedRepository extends EntityRepository
{
}
